controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

modules:
    resource:
        path: ../src/Module/
        namespace: App\Module
    type: attribute

infrastructure:
    resource:
        path: ../src/Infrastructure/
        namespace: App\Infrastructure
    type: attribute
