framework:
    messenger:
        default_bus: messenger.bus.default
        transports:
            # Example DSN for doctrine transport:
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # Use DSN from env; define MESSENGER_TRANSPORT_DSN in .env
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 60000
            failed:
                dsn: '%env(MESSENGER_FAILURE_TRANSPORT_DSN)%'
        failure_transport: failed
        routing:
            App\Module\Order\Message\OrderCreatedMessage: async
            App\Module\Order\Message\OrderStatusChangedMessage: async
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_transaction
