nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'X-Cart-Token', 'X-CSRF-Token']
        expose_headers: ['Link', 'X-Cart-Token', 'X-Request-Id']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'X-Cart-Token', 'X-CSRF-Token']
            expose_headers: ['Link', 'X-Cart-Token', 'X-Request-Id']
            allow_credentials: true
            max_age: 3600
