import { useEffect, useState } from 'react';
import { SiteLayout } from '@/shared/components/SiteLayout';
import { useDocumentTitle } from '@/shared/hooks/useDocumentTitle';
import { ErrorState, LoadingState, FeedbackMessage } from '@/shared/components/ui/page-state';
import { formatEuroCents, formatFrenchDate } from '@/shared/lib/formatters';
import { getHttpErrorMessage } from '@/shared/lib/httpClient';
import { downloadMyTradeInReceipt, fetchMyTradeIns, respondToTradeIn } from '../api';
import { downloadBlob } from '@/shared/lib/downloadFile';
import type { TradeInDto } from '../types';

export const MyTradeInsPage = () => { useDocumentTitle('Mes reprises'); const [items, setItems] = useState<TradeInDto[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void fetchMyTradeIns().then(setItems).catch((e) => setError(getHttpErrorMessage(e))).finally(() => setLoading(false)); }, []);
  const respond = async (id: number, action: 'accept' | 'decline') => { try { await respondToTradeIn(id, action); setItems((current) => current.map((item) => item.id === id ? { ...item, status: action === 'accept' ? 'accepted' : 'declined', statusLabel: action === 'accept' ? 'Offre acceptée' : 'Offre refusée' } : item)); setMessage(action === 'accept' ? 'Votre accord a été enregistré.' : 'Votre refus a été enregistré.'); } catch (e) { setError(getHttpErrorMessage(e)); } };
  const downloadReceipt = async (id: number, reference: string) => { try { downloadBlob(await downloadMyTradeInReceipt(id), `justificatif-reprise-${reference}.pdf`); } catch (downloadError) { setError(getHttpErrorMessage(downloadError)); } };
  return <SiteLayout><div className="container mx-auto px-4 py-8"><h1 className="text-2xl font-semibold mb-4">Mes reprises</h1>{message && <FeedbackMessage variant="success">{message}</FeedbackMessage>}{loading && <LoadingState>Chargement de vos demandes…</LoadingState>}{error && <ErrorState>{error}</ErrorState>}{!loading && !error && items.length === 0 && <p>Aucune demande de reprise pour le moment.</p>}<div className="space-y-4">{items.map((item) => <article key={item.id} className="rounded border border-brand-100 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{item.reference} — {item.productName}</h2><p className="text-sm text-stone-600">Demande du {formatFrenchDate(item.createdAt) ?? '—'} · {item.statusLabel}</p></div>{item.offerCents !== null && <strong>{formatEuroCents(item.offerCents)}</strong>}</div><p className="mt-3">Estimation indicative : {formatEuroCents(item.estimatedMinCents)} à {formatEuroCents(item.estimatedMaxCents)}</p>{item.adminNote && <p className="mt-2 rounded bg-stone-50 p-3">Message de Hociatec : {item.adminNote}</p>}{item.voucherCode && <p className="mt-3 rounded bg-emerald-50 p-3">Votre avoir client : <strong className="font-mono">{item.voucherCode}</strong></p>}{item.status === 'offer_sent' && <div className="mt-4 flex gap-3"><button className="register-form__submit" type="button" onClick={() => void respond(item.id, 'accept')}>Accepter l’offre</button><button className="catalog-admin-actions__delete" type="button" onClick={() => void respond(item.id, 'decline')}>Refuser</button></div>}{item.receiptAvailable && <button type="button" className="mt-4 underline" onClick={() => void downloadReceipt(item.id, item.reference)}>Télécharger mon justificatif PDF</button>}</article>)}</div></div></SiteLayout>;
};
