<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260726172000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store the customer voucher code generated by a trade-in closure';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE trade_in_requests ADD voucher_code VARCHAR(64) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE trade_in_requests DROP voucher_code');
    }
}
