import {
  ActivationPage,
  AppointmentBookingPage,
  BetaTestPage,
  CartPage,
  CatalogSearchPage,
  CategoryPage,
  CguPage,
  CgvPage,
  ContactPage,
  CreateQuotePage,
  ForgotPasswordPage,
  GlobalSearchPage,
  HomePage,
  LoginPage,
  MobileCheckoutReturnPage,
  MentionsPage,
  NewsDetailPage,
  NewsListPage,
  PrivacyPage,
  ProductPage,
  RegisterPage,
  ResetPasswordPage,
  SellingTypePage,
  ServiceDetailPage,
  ServicesCatalogPage,
  TrainingDetailPage,
  TrainingsCatalogPage,
  TradeInPage,
} from './PublicRoutePages';
import type { AppRouteDefinition } from './RouteDefinition';

export const publicRoutes: AppRouteDefinition[] = [
  { path: '/', element: <HomePage /> },
  { path: '/login', element: <LoginPage /> },
  { path: '/register', element: <RegisterPage /> },
  { path: '/forgot-password', element: <ForgotPasswordPage /> },
  { path: '/reset-password/:token', element: <ResetPasswordPage /> },
  { path: '/contact', element: <ContactPage /> },
  { path: '/beta-test', element: <BetaTestPage /> },
  { path: '/legal/cgu', element: <CguPage /> },
  { path: '/legal/cgv', element: <CgvPage /> },
  { path: '/legal/confidentialite', element: <PrivacyPage /> },
  { path: '/legal/mentions-legales', element: <MentionsPage /> },
  { path: '/activation/:token', element: <ActivationPage /> },
  { path: '/catalogue/produits/:slug', element: <ProductPage /> },
  { path: '/catalogue/recherche', element: <CatalogSearchPage /> },
  { path: '/catalogue/vente', element: <SellingTypePage sellingType="sale" title="Vente" /> },
  { path: '/catalogue/location', element: <SellingTypePage sellingType="rental" title="Location" /> },
  { path: '/catalogue/:slug', element: <CategoryPage /> },
  { path: '/recherche', element: <GlobalSearchPage /> },
  { path: '/actualites', element: <NewsListPage /> },
  { path: '/actualites/:slug', element: <NewsDetailPage /> },
  { path: '/services', element: <ServicesCatalogPage /> },
  { path: '/services/:serviceId', element: <ServiceDetailPage /> },
  { path: '/formations', element: <TrainingsCatalogPage /> },
  { path: '/formations/:slug', element: <TrainingDetailPage /> },
  { path: '/panier', element: <CartPage /> },
  { path: '/checkout/app-return', element: <MobileCheckoutReturnPage /> },
  { path: '/devis/nouveau', element: <CreateQuotePage /> },
  { path: '/appointments/book', element: <AppointmentBookingPage /> },
  { path: '/reprise', element: <TradeInPage /> },
];
