import type { Dispatch, SetStateAction } from 'react';

import type { PromotionAudienceDefinition } from '@/features/admin/promotions/api';
import type { PromotionFormState } from '@/features/admin/promotions/types/promotionFormTypes';

export const PromotionFormFields = ({ form, setForm, audiences }: { form: PromotionFormState; setForm: Dispatch<SetStateAction<PromotionFormState>>; audiences: Record<string, PromotionAudienceDefinition> }) => (
  <>
    <label className="register-form__field"><span className="register-form__label">Nom</span><input className="register-form__input" value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} /></label>
    <label className="register-form__field"><span className="register-form__label">Slug</span><input className="register-form__input" value={form.slug} onChange={(event) => setForm((current) => ({ ...current, slug: event.target.value }))} /></label>
    <label className="register-form__field"><span className="register-form__label">Description</span><input className="register-form__input" value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} /></label>
    <div className="grid gap-4 md:grid-cols-2"><label className="register-form__field"><span className="register-form__label">Type de remise</span><select className="register-form__input" value={form.discountType} onChange={(event) => setForm((current) => ({ ...current, discountType: event.target.value as 'percent' | 'fixed_cents' }))}><option value="percent">Pourcentage</option><option value="fixed_cents">Montant fixe en euros</option></select></label><label className="register-form__field"><span className="register-form__label">Valeur {form.discountType === 'percent' ? '(%)' : '(EUR)'}</span><input className="register-form__input" type="number" min={1} step={form.discountType === 'percent' ? 1 : 0.01} value={form.discountValue} onChange={(event) => setForm((current) => ({ ...current, discountValue: event.target.value }))} placeholder={form.discountType === 'percent' ? 'Ex: 10' : 'Ex: 15,00'} /></label></div>
    <label className="register-form__field"><span className="register-form__label">Audience</span><select className="register-form__input" value={form.audienceKey} onChange={(event) => setForm((current) => ({ ...current, audienceKey: event.target.value }))}>{Object.entries(audiences).map(([key, audience]) => <option key={key} value={key}>{audience.label}</option>)}</select></label>
    {audiences[form.audienceKey] ? <div className="rounded-2xl border border-brand-100 bg-brand-50 px-4 py-4 text-sm text-stone-700"><strong className="block text-brand-900">{audiences[form.audienceKey]?.label}</strong><span>{audiences[form.audienceKey]?.description}</span></div> : null}
    <label className="register-form__field"><span className="register-form__label">Panier minimum en euros</span><input className="register-form__input" type="number" min={0} step={0.01} value={form.minimumCartTotalEuros} onChange={(event) => setForm((current) => ({ ...current, minimumCartTotalEuros: event.target.value }))} /></label>
    {form.audienceKey === 'new_users' && <label className="register-form__field"><span className="register-form__label">Inscription depuis moins de X jours</span><input className="register-form__input" type="number" min={1} value={form.registeredDays} onChange={(event) => setForm((current) => ({ ...current, registeredDays: event.target.value }))} /></label>}
    {form.audienceKey === 'loyal_customers' && <label className="register-form__field"><span className="register-form__label">Nombre minimum de commandes</span><input className="register-form__input" type="number" min={2} value={form.minimumOrders} onChange={(event) => setForm((current) => ({ ...current, minimumOrders: event.target.value }))} /></label>}
    {form.audienceKey === 'inactive_customers' && <label className="register-form__field"><span className="register-form__label">Inactivité depuis X jours</span><input className="register-form__input" type="number" min={30} value={form.inactiveDays} onChange={(event) => setForm((current) => ({ ...current, inactiveDays: event.target.value }))} /></label>}
    <div className="grid gap-4 md:grid-cols-2"><label className="register-form__field"><span className="register-form__label">Début</span><input className="register-form__input" type="datetime-local" value={form.startsAt} onChange={(event) => setForm((current) => ({ ...current, startsAt: event.target.value }))} /></label><label className="register-form__field"><span className="register-form__label">Fin</span><input className="register-form__input" type="datetime-local" value={form.endsAt} onChange={(event) => setForm((current) => ({ ...current, endsAt: event.target.value }))} /></label></div>
    <label className="booking__checkbox"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm((current) => ({ ...current, isActive: event.target.checked }))} />Promotion active</label>
  </>
);
